// Generated by eve. Do not edit by hand.
import { POST } from "../../../node_modules/.pnpm/eve@0.11.10_ai@7.0.0-beta.178_zod@4.1.11_/node_modules/eve/.eve/workflow-cache/9d1cda8f7cc5/workflows.mjs";

export default async ({ req }) => {
  return await POST(req);
};
