// Generated by eve. Do not edit by hand.
import type { InferChannelMetadata } from "eve/channels";

declare module "eve/channels" {
  interface ChannelMetadataMap {
    readonly "channel:linear": InferChannelMetadata<typeof import("../../agent/channels/linear.js").default>;
    readonly "channel:slack": InferChannelMetadata<typeof import("../../agent/channels/slack.js").default>;
  }
  interface ChannelReferenceMap {
    readonly "channel:linear": typeof import("../../agent/channels/linear.js").default;
    readonly "channel:slack": typeof import("../../agent/channels/slack.js").default;
  }
}
