// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/linear.ts";
import * as module_2 from "../../agent/channels/slack.ts";
import * as module_3 from "../../agent/connections/linear.ts";
import * as module_4 from "../../agent/schedules/cycle-health.ts";
import * as module_5 from "../../agent/schedules/daily-triage-digest.ts";
import * as module_6 from "../../agent/schedules/p1-monitoring.ts";
import * as module_7 from "../../agent/schedules/weekly-backlog-hygiene.ts";
import * as module_8 from "../../agent/schedules/weekly-initiative-updates.ts";
import * as module_9 from "../../agent/schedules/weekly-project-summary.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/linear.ts": module_1,
                  "channels/slack.ts": module_2,
                  "connections/linear.ts": module_3,
                  "schedules/cycle-health.ts": module_4,
                  "schedules/daily-triage-digest.ts": module_5,
                  "schedules/p1-monitoring.ts": module_6,
                  "schedules/weekly-backlog-hygiene.ts": module_7,
                  "schedules/weekly-initiative-updates.ts": module_8,
                  "schedules/weekly-project-summary.ts": module_9
                })
            })
    })
});

export default moduleMap;
